name: Github Robot
on:
  issue_comment:
    types:
      - created
env:
  GH_TOKEN: "${{ secrets.ORG_REPO_TOKEN }}"
jobs:
  comment:
    if: startswith(github.event.comment.body, '/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Gh Robot for Sealos
        uses: nxpkg/robot@main
        with:
          version: v2.0.0
        env:
          SEALOS_TYPE: "/comment"
          GH_TOKEN: "${{ secrets.ORG_REPO_TOKEN }}"
